### ISSUE TITLE
Why this lib so dead?

### ISSUE THREAD

**Issue by murat-mehmet** [KnisterPeter/pretend#372]
This is the best (and almost only) declarative lib that I could find which works best across all of my projects (Vanilla React, Next.js SSR, Vanilla React Native, Expo managed RN etc). I'm using it quite a while and it's working great. Is there any more popular alternative that people are using? I would like to see this lib go over 10k stars :) Thousands of thanks for taking your time to share this with the world.

**Comment by KnisterPeter** [comment]
@murat-mehmet Its not dead. I'm using it, but I don't miss any current feature. Feel free to create feature requests.

And thanks for you kind words.
