### ISSUE TITLE
append dynamic headers

### ISSUE THREAD

**Issue by murat-mehmet** [KnisterPeter/pretend#430]
Currently the only ways to add a header is by using @Header(...) decorator or an interceptor. I am currently in need of generating a header and add it to the request in runtime. I think I will go with interceptor pattern but it would be great to have appendHeaders in GET,POST,.. decorators and add the latest object as header to the request. I checked the code and it seems possible but appendQuery index checks are little obstructive there. If it seems easy for you, could you try to implement please, otherwise I will have a look again in some free time.

**Comment by KnisterPeter** [comment]
Hi @murat-mehmet,
I don't like to overload the GET,POST decorators any more. They are already quite complex.
And the interceptors are exactly there for all dynamic things

**Comment by murat-mehmet** [comment]
yea but interceptors are too generic for something like adding a special header just for an endpoint. Other endpoints won't need that header. But I agree that @Get('...',false, true) wont look good either. The ideal way would be adding parameters with decorators. It would look like 
@Get('my_endpoint/{id}')
my_endpoint(@Param('id') id, @Query() query, @Body() body, @Header() headers)
it would be much more elegant and flexible this way.

**Comment by KnisterPeter** [comment]
I vote for not adding this right now. Maybe I'll do that at a later point.
Another idea (favored for me, but also not thought on enough) would be to add interceptors for specific methods.
Anyway, right now I would like to close this until I come back to it.
